/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_jnihello_NDKTools */

#ifndef _Included_com_android_jnihello_NDKTools
#define _Included_com_android_jnihello_NDKTools
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_jnihello_NDKTools
 * Method:    getStringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_android_jnihello_NDKTools_getStringFromJNI
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
